#!/bin/bash
# Make table and insert data

echo "SELECT * FROM users;" | mysql -uroot -p holberton
#ERROR 1146 (42S02) at line 1: Table 'holberton.users' doesn't exist

cat 1-country_users.sql | mysql -uroot -p holberton
echo 'INSERT INTO users (email, name, country) VALUES ("bob@dylan.com", "Bob", "US");' | mysql -uroot -p holberton
echo 'INSERT INTO users (email, name, country) VALUES ("sylvie@dylan.com", "Sylvie", "CO");' | mysql -uroot -p holberton
echo 'INSERT INTO users (email, name, country) VALUES ("jean@dylan.com", "Jean", "FR");' | mysql -uroot -p holberton
#ERROR 1265 (01000) at line 1: Data truncated for column 'country' at row 1
echo 'INSERT INTO users (email, name) VALUES ("john@dylan.com", "John");' | mysql -uroot -p holberton
echo "SELECT * FROM users;" | mysql -uroot -p holberton
Enter password: 
id  email   name    country
1   bob@dylan.com   Bob US
2   sylvie@dylan.com    Sylvie  CO
3   john@dylan.com  John    US